using FlashSale.Domain.Enums;

namespace FlashSale.Domain.Entities;

/// <summary>
/// A single sellable seat. This is the hot, contended row in a flash sale:
/// thousands of buyers race for the same row, so correctness is enforced by
/// SQL Server's <c>rowversion</c> column plus optimistic concurrency
/// (configured in <c>ApplicationDbContext.OnModelCreating</c>).
/// </summary>
public class Ticket
{
    public Guid Id { get; set; }

    public Guid EventId { get; set; }

    /// <summary>Human-readable seat label, e.g. "A-12" or "Block B / Row 4 / Seat 19".</summary>
    public string SeatNumber { get; set; } = string.Empty;

    /// <summary>
    /// One of <see cref="TicketStatus"/>: <c>Available</c>, <c>Reserved</c> or <c>Sold</c>.
    /// Mapped as a string so the stored value stays self-documenting.
    /// </summary>
    public string Status { get; set; } = nameof(TicketStatus.Available);

    /// <summary>
    /// The buyer who currently holds (or bought) this seat. Null while available.
    /// </summary>
    public Guid? AssignedUserId { get; set; }

    /// <summary>
    /// Expiry of the current hold. Set when the seat moves to <c>Reserved</c> so an
    /// abandoned checkout can be reclaimed by the reservation sweeper worker.
    /// </summary>
    public DateTimeOffset? ReservedUntilUtc { get; set; }

    /// <summary>Price in minor units (pence/cents) to match <see cref="Event"/>.</summary>
    public long PriceInMinorUnits { get; set; }

    /// <summary>
    /// SQL Server <c>rowversion</c> token. EF Core maps this to a concurrency token
    /// via <c>IsRowVersion()</c>; it is generated by the database and is read-only
    /// for the application, which is exactly what makes the
    /// <c>DbUpdateConcurrencyException</c> path in the booking endpoint reachable.
    /// </summary>
    public byte[] RowVersion { get; set; } = [];

    public Event Event { get; set; } = null!;

    public User? AssignedUser { get; set; }

    /// <summary>
    /// True when the seat is free to claim right now.
    /// </summary>
    public bool IsClaimable =>
        Status == nameof(TicketStatus.Available) ||
        (Status == nameof(TicketStatus.Reserved) && ReservedUntilUtc is not null && ReservedUntilUtc <= DateTimeOffset.UtcNow);
}